import { LightningElement, api } from 'lwc';
import { createElement } from 'lwc';
import UiJobCaller from 'c/uiJobCaller';

describe('c-ui-job-caller', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ui-job-caller', {
            is: UiJobCaller
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});